### ISSUE TITLE
DY2 snow height adjustments

### ISSUE THREAD

**Issue by jasonebox** [GEUS-Glaciology-and-Climate/GC-Net-level-1-data-processing#100]
here are adjustments, see before, after. Its an improvement, but makes me think working with L0 data first may ultimately produce a better result. There remains some filtering of upward spikes from snow drift, i.e. sonic reflection off of saltation and suspension drift layer

          if nicknames[0]=='DY2':
            t=datetime(1998, 4, 19)
            df['HS1'][t:]+=0.35
            t=datetime(2001, 6, 13)
            value=-0.16
            df['HS1'][t:]+=value
            df['HS2'][t:]+=value
            t=datetime(2000, 5, 13)
            value=0.15
            df['HS1'][t:]+=value
            df['HS2'][t:]+=value
            t=datetime(2003, 9, 1)
            df['HS1'][t:]+=0.15
            t=datetime(2004, 5, 31)
            df['HS2'][t:]-=0.66
            t=datetime(2006, 5, 6)
            df['HS1'][t:]+=0.3
            t=datetime(2009, 5, 16)
            df['HS1'][t:]+=0.55
            t=datetime(2010, 1, 11)
            value=0.6 # this offset is to span a gap, assumes slope from 2005 to 2009, uncertain!
            df['HS1'][t:]+=value
            df['HS2'][t:]+=value
            t0=datetime(2010, 4, 28)
            t1=datetime(2010, 5, 1)
            value=2.6 # removes a 3 day offset spike
            df['HS1'][t0:t1]-=value
            df['HS2'][t0:t1]-=value
            t=datetime(2010, 5, 1)
            value=0.26
            df['HS1'][t:]+=value
            df['HS2'][t:]+=value            # df['HS1'][t:]+=0.35
            t=datetime(2015, 5, 27)
            df['HS1'][t:]-=0.31
            t=datetime(2017, 1, 11)
            value=0.1 # this offset is to span a gap, assumes slope from 2010 to 2016, uncertain!
            df['HS1'][t:]+=value
            df['HS2'][t:]+=value
            t=datetime(2018, 5, 10)
            df['HS1'][t:]+=0.12
            t=datetime(2019, 5, 23)
            df['HS2'][t:]-=0.2         
before
![image](https://user-images.githubusercontent.com/32133350/211145510-73d87a61-6ae6-41ac-a7e2-c98983b07b1b.png)
after
![image](https://user-images.githubusercontent.com/32133350/211146562-80eb3d77-a3a4-4fd8-9f4b-1e97b6eb9998.png)

**Comment by BaptisteVandecrux** [comment]
Fixed in the latest commit:
![image](https://user-images.githubusercontent.com/35140661/211560134-64c4df95-ab82-48f2-bb9d-71f1eb3a8c3b.png)
