### ISSUE TITLE
Summit snow height adjustments

### ISSUE THREAD

**Issue by jasonebox** [GEUS-Glaciology-and-Climate/GC-Net-level-1-data-processing#101]
adjustment parameters below graphics...

before
![image](https://user-images.githubusercontent.com/32133350/211157447-7bfbd9f6-8b98-4277-865d-6ae4a0594f4c.png)

after
![image](https://user-images.githubusercontent.com/32133350/211157463-6a15c1a1-57e7-464b-bc84-f696814d9e29.png)

        if nicknames[0]=='SUM':
            t=datetime(1997, 5, 22)
            df['HS1'][t:]+=0.12
            t=datetime(1999, 1, 1)
            value=0.27
            df['HS1'][t:]+=value
            df['HS2'][t:]+=value            
            df['HS1'][t:]+=0.05
            t=datetime(2001, 6, 15)
            df['HS1'][t:]+=0.28
            t=datetime(2003, 11, 30)
            df['HS2'][t:]+=0.1
            t=datetime(2005, 5, 30)
            df['HS2'][t:]+=0.05
            t=datetime(2009, 4, 10)
            df['HS1'][t:]+=0.2
            t=datetime(2010, 8, 10)
            df['HS1'][t:]-=0.15
            df['HS2'][t:]-=0.35
            t=datetime(2018, 1, 1)
            value=0.2
            df['HS1'][t:]+=value
            df['HS2'][t:]+=value

**Comment by BaptisteVandecrux** [comment]
Fixed in latest commit:
![image](https://user-images.githubusercontent.com/35140661/211559958-16a258c5-8739-4bb6-883b-159ce83411ff.png)
