### ISSUE TITLE
NAU snow height adjustments

### ISSUE THREAD

**Issue by jasonebox** [GEUS-Glaciology-and-Climate/GC-Net-level-1-data-processing#102]
adjustment parameters below graphics, still lots of filterable noise at ~10 cm scale

before
![image](https://user-images.githubusercontent.com/32133350/211189663-6eb15cbf-1836-4c0f-bc0a-7340df792f05.png)

after
![image](https://user-images.githubusercontent.com/32133350/211189648-adf29bb5-4009-46c9-8bdc-e621fa72f8db.png)

        if nicknames[0]=='NAU':
            t=datetime(1997, 1, 11)
            df['HS1'][t:]+=0.87
            t=datetime(1999, 5, 14)
            df['HS1'][t:]-=1.85
            df['HS2'][t:]-=0.3
            t0=datetime(1999, 5, 1) # filter downward spikes
            t1=datetime(2000, 8, 1) 
            df['HS1'][t0:t1][df['HS1'][t0:t1]<2.5]=np.nan
            df['HS2'][t0:t1][df['HS2'][t0:t1]<2.5]=np.nan
            t=datetime(2003, 5, 14)
            df['HS1'][t:]+=0.05
            t0=datetime(2002, 5, 1) # filter downward spikes
            t1=datetime(2004, 8, 1) 
            df['HS1'][t0:t1][df['HS1'][t0:t1]<6]=np.nan
            df['HS2'][t0:t1][df['HS2'][t0:t1]<6]=np.nan
            t=datetime(2005, 5, 25)
            df['HS1'][t:]+=0.3
            t=datetime(2005, 8, 22)
            df['HS1'][t:]+=0.25
            t0=datetime(2005, 4, 28)
            t1=datetime(2007, 9, 1) # filter upward spikes
            df['HS1'][t0:t1][df['HS1'][t0:t1]>11.5]=np.nan
            df['HS2'][t0:t1][df['HS2'][t0:t1]>11.5]=np.nan
            t0=datetime(2007, 9, 1)
            t1=datetime(2008, 9, 1) # filter upward spikes
            df['HS1'][t0:t1][df['HS1'][t0:t1]>12]=np.nan
            df['HS2'][t0:t1][df['HS2'][t0:t1]>12]=np.nan
            t0=datetime(2008, 9, 1)
            t1=datetime(2009, 9, 1) # filter upward spikes
            df['HS1'][t0:t1][df['HS1'][t0:t1]>13]=np.nan
            df['HS2'][t0:t1][df['HS2'][t0:t1]>13]=np.nan
            t=datetime(2009, 1, 1)
            df['HS1'][t:]+=0.14
            t=datetime(2011, 10, 1)
            df['HS1'][t:]+=0.05
            t=datetime(2013, 6, 1)
            df['HS1'][t:]+=0.05
            t=datetime(2013, 1, 1)
            df['HS2'][t:]+=0.05
            t=datetime(2013, 6, 2)
            df['HS1'][t:]+=0.1
            t0=datetime(2013, 5, 1) # filter downward spikes
            t1=datetime(2013, 8, 1) 
            df['HS1'][t0:t1][df['HS1'][t0:t1]<14.9]=np.nan
            df['HS2'][t0:t1][df['HS2'][t0:t1]<14.9]=np.nan
            t1=datetime(2014, 8, 1) # filter upward spikes
            df['HS1'][t0:t1][df['HS1'][t0:t1]>16]=np.nan
            df['HS2'][t0:t1][df['HS2'][t0:t1]>16]=np.nan
            t=datetime(2018, 1, 1)
            df['HS1'][t:]+=0.5
            df['HS2'][t:]+=1.

**Comment by BaptisteVandecrux** [comment]
Fixed in the latest commit:
![image](https://user-images.githubusercontent.com/35140661/211559818-1c9bbcb6-0896-453a-810c-71709a948fed.png)
