### ISSUE TITLE
Swiss Camp snow height air t correction

### ISSUE THREAD

**Issue by jasonebox** [GEUS-Glaciology-and-Climate/GC-Net-level-1-data-processing#105]
seems to be missing air t correction for HS1, HS2 for the first part of the record
![image](https://user-images.githubusercontent.com/32133350/212538280-c8429cf7-a38e-4eae-be94-35252e8587f4.png)

**Comment by jasonebox** [comment]
ps. height adjustment recommendations coming in next issue

**Comment by BaptisteVandecrux** [comment]
Interestingly the diurnal fluctuation came from an over-correction of air temperature effect

![image](https://user-images.githubusercontent.com/35140661/212670181-79e7be9f-4b8a-4908-a701-4dbafe587160.png)

In blue you have HW_raw
In yellow HW_raw * np.sqrt((T+ 273.15) / 273.15)     ---> this is the usual correction
In yellow HW_raw / np.sqrt((T+ 273.15) / 273.15)     ---> this is means removing the correction

So the diurnal variation is removed when "uncorrecting" the data for air temp.

This comes from the fact that for data before 2007, we use the c level files that @jasonebox provided.
This apparent correction is inherited from the processing of that c level file.

In the future, we could consider processing the logger files for the older years.
That is what was done for the 10m tower.
But that represent quite some work.

**Comment by BaptisteVandecrux** [comment]
Corrected in the last commit
