### ISSUE TITLE
SwissCamp upward and downward SW wiring swapped

### ISSUE THREAD

**Issue by jasonebox** [GEUS-Glaciology-and-Climate/GC-Net-level-1-data-processing#86]
```
  if site=='SwissCamp':
      df=adjuster(site,df,['ISWR','OSWR'],2013,1,1,'swap',2018,12,31,'upward and downward SW wiring swapped?',0.5)
      df=adjuster(site,df,['ISWR','OSWR'],2019,1,1,'swap',2019,12,31,'upward and downward SW wiring swapped?',0.5)
      df=adjuster(site,df,['ISWR','OSWR'],2020,1,1,'swap',2020,12,31,'upward and downward SW wiring swapped?',0.5)
      df=adjuster(site,df,['ISWR','OSWR'],2021,1,1,'swap',2021,12,31,'upward and downward SW wiring swapped?',0.5)
```
see [https://github.com/jasonebox/GCN_albedo/tree/main/metadata/adjustments/SwissCamp](https://github.com/jasonebox/GCN_albedo/tree/main/metadata/adjustments/SwissCamp)

and [https://github.com/jasonebox/GCN_albedo/blob/main/src/GCN_albedo.py](https://github.com/jasonebox/GCN_albedo/blob/main/src/GCN_albedo.py)

**Comment by BaptisteVandecrux** [comment]
Thanks, now added in the adjustment list:
[20120510T00:00:00+00:00,,ISWR,swap_with_OSWR,0,Not reported. Manual shift adj by bav.](https://github.com/GEUS-Glaciology-and-Climate/GC-Net-level-1-data-processing/blob/cae4968c368c05078b71a261a15d5a8ab0368974/metadata/adjustments/Swiss%20Camp.csv#L9)

Will be added to the nex reprocessing
