### ISSUE TITLE
CP1 snow height adjustments

### ISSUE THREAD

**Issue by jasonebox** [GEUS-Glaciology-and-Climate/GC-Net-level-1-data-processing#99]
I 1.) found offsets that align the 2 HS series better and 2.) that make adjustments to the long term trend when there is a too large of a gap. 2.) should be revisited once we have a better handle on the real long term trend, i.e. underscores the value of having updater cores overlapping with the last cores.

There remain spikes to be filtered.

before
![image](https://user-images.githubusercontent.com/32133350/211140268-33158099-ea54-41a5-a8c1-00e2a0300e19.png)

after
![image](https://user-images.githubusercontent.com/32133350/211140281-bbcb3fd5-bf20-421d-90a0-5af1175bd688.png)

here are the adjustment factors

        if nicknames[0]=='CP1':
            t=datetime(1996, 5, 21)
            df['HS1'][t:]+=0.31
            t=datetime(1998, 6, 9)
            df['HS1'][t:]-=0.51
            df['HS2'][t:]-=0.38
            t=datetime(1999, 5, 1)
            df['HS2'][t:]+=0.56
            df['HS1'][t:]+=0.47
            t=datetime(2003, 4, 1)
            df['HS1'][t:]+=0.5
            t=datetime(2005, 5, 2)
            df['HS1'][t:]-=0.4
            t=datetime(2011, 1, 1)
            value=1
            df['HS1'][t:]+=value
            df['HS2'][t:]+=value
            t=datetime(2008, 5, 5)
            df['HS2'][t:]-=0.25
            t=datetime(2016, 5, 5)
            df['HS2'][t:]+=0.75
            t=datetime(2017, 5, 22)
            df['HS1'][t:]-=0.46
            df['HS2'][t:]+=2.5

**Comment by BaptisteVandecrux** [comment]
Fixed in the commit last commit
![image](https://user-images.githubusercontent.com/35140661/211559733-ce4b0d92-4937-4d25-a6ab-560e5d78db1c.png)
